version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=backchannel
      - DB_PASSWORD=backchannel_password
      - DB_NAME=backchannel_db
      - JWT_SECRET=backchannel_jwt_secret_dev_only
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=backchannel_db
      - MYSQL_USER=backchannel
      - MYSQL_PASSWORD=backchannel_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: 